require 'hoe'
require './lib/punks/version.rb'

###
# hack/ quick fix for broken intuit_values - overwrite with dummy
class Hoe
  def intuit_values( input ); end
end



Hoe.spec 'punks' do

  self.version = Pixelart::Module::Punks::VERSION

  self.summary = "punks - generate your own 24×24 (or 32×32) punk (incl. Matt & John's® ye olde punk v1/v2 anno 2017 style), phunk, philip, marilyn, saudi/sheik, man in black, hottie 'n' more (pixel) avatar / character images (off chain) from text attributes (via built-in spritesheet); incl. 2x/4x/8x zoom for bigger sizes and more"
  self.description = summary

  self.urls    = { home: 'https://github.com/cryptopunksnotdead/cryptopunks' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['pixelart', '>= 1.3.2'],
    ['backgrounds', '>= 0.2.0'],
    ['artfactory', '>= 0.2.0'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end
