#!/bin/sh

mkdir -p ~/Library/Frameworks
[ ! -d ~/Library/Tcl ] && cp -r Tcl ~/Library/Tcl
[ ! -d ~/Library/Frameworks/Tcl.framework ] && cp -r Tcl.framework ~/Library/Frameworks/Tcl.framework
[ ! -d ~/Library/Frameworks/Tk.framework ] && cp -r Tk.framework ~/Library/Frameworks/Tk.framework

export GLIMMER_APP_PREFIX="$(dirname "$BASH_SOURCE")"
DYLD_LIBRARY_PATH="$GLIMMER_APP_PREFIX/6.2.1_1/lib" "$GLIMMER_APP_PREFIX/ruby-3.0.2/bin/ruby" "$GLIMMER_APP_PREFIX/cryptopunks-gui/bin/cryptopunks-mac-gui.rb"
